export interface Employee {
  code?: any; // int(6) unsigned NOT NULL AUTO_INCREMENT,
  no?: any; // varchar(10) DEFAULT NULL,
  id?: any; // varchar(15) NOT NULL DEFAULT '',
  title?: any; // varchar(20) DEFAULT NULL,
  name?: any; // varchar(35) DEFAULT NULL,
  surname?: any; // varchar(35) DEFAULT NULL,
  nicname?: any; // varchar(20) DEFAULT NULL,
  type?: any; // enum('ข','ป','ช','พ','ร','ส','บ','อ','ศ','A') DEFAULT 'ช',
  person_id?: any; // varchar(20) DEFAULT NULL,
  position_n?: any; // varchar(10) DEFAULT NULL,
  pos_type?: any; // varchar(5) DEFAULT NULL,
  bank?: any; // int DEFAULT NULL,
  bank_branch?: any; // int DEFAULT NULL,
  bank_id?: any; // varchar(15) DEFAULT NULL,
  bank_id2?: any; // varchar(15) DEFAULT NULL,
  license_no?: any; // varchar(30) NOT NULL,
  position?: any; // varchar(100) DEFAULT NULL,
  level?: any; // varchar(100) DEFAULT NULL,
  textLevel?: any; // varchar(100) DEFAULT NULL,
  officecode?: any; // varchar(8) DEFAULT NULL,
  office?: any; // char(3) DEFAULT NULL,
  dep?: any; // varchar(20) DEFAULT NULL,
  department?: any; // varchar(10) DEFAULT NULL,
  unit?: any; // varchar(8) DEFAULT NULL,
  tax_no?: any; // varchar(20) DEFAULT NULL,
  tel?: any; // varchar(15) DEFAULT NULL,
  tel_home?: any; // varchar(20) DEFAULT NULL,
  tel_mobile?: any; // varchar(20) DEFAULT NULL,
  startdate?: any; // date NOT NULL DEFAULT '0000-00-00',
  expire?: any; // date NOT NULL DEFAULT '0000-00-00',
  gpf?: any; // tinyint(1) NOT NULL DEFAULT '0',
  gpf_rate?: any; // double(7,2) NOT NULL DEFAULT '0.00',
  pfund?: any; // tinyint(1) NOT NULL DEFAULT '0',
  pfund_rate?: any; // float(5,2) NOT NULL DEFAULT '0.00',
  pfundmoph?: any; // tinyint(1) NOT NULL DEFAULT '0',
  pfmo_rate?: any; // float(5,2) NOT NULL DEFAULT '0.00',
  soc?: any; // tinyint(1) NOT NULL DEFAULT '0',
  soc_rate?: any; // float(5,2) NOT NULL DEFAULT '0.00',
  assur_dd?: any; // tinyint(1) DEFAULT NULL,
  assur_no?: any; // int(2) DEFAULT NULL,
  id2?: any; // varchar(10) DEFAULT NULL,
  passwd?: any; // varchar(32) DEFAULT NULL,
  password?: any; // varchar(128) DEFAULT NULL,
  sha?: any; // varchar(128) DEFAULT NULL,
  hash?: any; // varchar(200) DEFAULT NULL,
  encr?: any; // varchar(200) DEFAULT NULL,
  conf?: any; // datetime DEFAULT NULL,
  ot_rate?: any; // float(11,2) DEFAULT '60.00',
  extra_rate?: any; // float(11,2) DEFAULT NULL,
  email?: any; // text,
  hn?: any; // varchar(10) DEFAULT NULL,
  trustweb?: any; // tinyint(1) NOT NULL DEFAULT '0',
  remark?: any; // text,
  inp_id?: any; // varchar(15) DEFAULT NULL,
  lastupdate?: any; // timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
}

export interface Payroll {
  id?: any; // int(11) unsigned NOT NULL AUTO_INCREMENT,
  monthly?: any; // varchar(4) NOT NULL,
  no?: any; // char(5) NOT NULL,
  month?: any; // int(2) NOT NULL,
  year?: any; // int(2) NOT NULL,
  salary?: any; // double(10,2) DEFAULT NULL,
  tax?: any; // double(8,2) DEFAULT NULL,
  assur_dd?: any; // double(7,2) DEFAULT NULL,
  saving?: any; // double(9,2) DEFAULT NULL,
  kid?: any; // double(9,2) DEFAULT NULL,
  gpf?: any; // double(8,2) DEFAULT NULL,
  pfund?: any; // double(8,2) DEFAULT NULL,
  pfundmoph?: any; // double(8,2) NOT NULL DEFAULT '0.00',
  soc?: any; // double(8,2) DEFAULT NULL,
  isconfirm?: any; // enum('0','1') DEFAULT '0',
  received?: any; // double(10,2) DEFAULT NULL,
  paid?: any; // double(10,2) DEFAULT NULL,
  remark?: any; // text,
  lastupdate?: any; // timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
}

export interface PayrollItem {
  ref?: any; // int(11) NOT NULL AUTO_INCREMENT,
  monthly?: any; // varchar(4) DEFAULT NULL,
  no?: any; // char(5) NOT NULL,
  month?: any; // int(2) NOT NULL,
  year?: any; // int(2) NOT NULL,
  type?: any; // int(4) NOT NULL,
  item?: any; // int(4) DEFAULT NULL,
  item_type?: any; // enum('P','R') DEFAULT 'P',
  budget_source?: any; // varchar(4) NOT NULL DEFAULT 'INH',
  money?: any; // float(13,4) DEFAULT NULL,
  detail?: any; // longtext,
  isconfirm?: any; // enum('0','1') DEFAULT '0',
}

export interface LibPaytype {
  code?: any; // int(4) NOT NULL,
  text?: any; // varchar(100) DEFAULT NULL,
  type?: any; // varchar(10) DEFAULT NULL,
  default_source?: any; // varchar(4) NOT NULL DEFAULT 'HOSP' COMMENT 'in hospital, cgd',
  remark?: any; // text,
  lastupdate?: any; // timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
}

export interface LibBank {
  bank_id?: any; // int(3) unsigned NOT NULL AUTO_INCREMENT,
  bank_code?: any; // varchar(10) NOT NULL DEFAULT '',
  bank_name?: any; // varchar(80) NOT NULL DEFAULT '',
  detail?: any; // text,
  swiftcode?: any; // varchar(20) DEFAULT NULL,
  isactive?: any; // tinyint(4) NOT NULL DEFAULT '1',
  lastupdate?: any; // timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,  
}

export interface LibBankBranch {
  branch_id?: any; // int(5) unsigned NOT NULL AUTO_INCREMENT,
  bank?: any; // int(3) unsigned DEFAULT NULL,
  branch_name?: any; // varchar(80) DEFAULT NULL,
  address?: any; // varchar(100) DEFAULT NULL,
  addcode?: any; // varchar(6) DEFAULT NULL,
  tel?: any; // varchar(30) DEFAULT NULL,
  contact?: any; // varchar(100) DEFAULT NULL,
  isactive?: any; // tinyint(4) NOT NULL DEFAULT '1',
  detail?: any; // text,
  remark?: any; // text,
  lastupdate?: any; // timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,  
}

export interface LibType {
  code?: any; // varchar(2) NOT NULL,
  name?: any; // varchar(50) DEFAULT NULL,
  isactive?: any; // tinyint(4) NOT NULL DEFAULT '1',
  remark?: any; // longtext,
}

export interface Logon {
  ref?: any; // int(7) NOT NULL AUTO_INCREMENT,
  no?: any; // varchar(11) NOT NULL DEFAULT '',
  ip?: any; // varchar(15) NOT NULL DEFAULT '',
  date?: any; // datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  time?: any; // time NOT NULL DEFAULT '00:00:00',
  date_out?: any; // datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  time_out?: any; // time NOT NULL DEFAULT '00:00:00',
  sessn?: any; // varchar(128) NOT NULL DEFAULT '',
  module?: any; // varchar(12) DEFAULT NULL,
  remark?: any; // text,
}

